### ISSUE TITLE
Step 8 detailed instructions

### ISSUE THREAD

**Issue by LoganSimonsen** [DevMountain/home-loan-wizard#11]
On step 8 in the detailed instructions it shows that we should export this function as default:
export **default** updateCity( city ) {
  return {
    type: UPDATE_CITY,
    payload: city
  }
}

however the solution is:
export **function** updateCity( city ) {
  return {
    type: UPDATE_CITY,
    payload: city
  }
}

**Comment by steven-isbell** [comment]
Issue Resolved
